patch:
  schema_list:
    - schema: luna_pinyin
    - schema: luna_pinyin_simp
    - schema: luna_pinyin_fluency
    - schema: luna_pinyin_tw
    - schema: bopomofo
    - schema: bopomofo_tw
    - schema: cangjie5
    - schema: stroke
    - schema: terra_pinyin
