theme = "rose_pine"

[editor]
line-number = "relative"
completion-replace = true
completion-trigger-len = 1
rulers = [80]
popup-border = "all"
end-of-line-diagnostics = "hint"

[editor.file-picker]
hidden = false
git-ignore = false

[editor.search]
smart-case = false

[editor.soft-wrap]
enable = true

[editor.inline-diagnostics]
cursor-line = "warning"
