vim.g.mapleader = " "
vim.g.maplocalleader = "\\"
vim.opt.cursorcolumn = true
vim.opt.colorcolumn = "80"
vim.opt.expandtab = true
vim.opt.splitright = true
vim.opt.swapfile = false
vim.opt.undofile = true
vim.opt.smartindent = true
vim.opt.shiftwidth = 4
vim.opt.number = true
vim.opt.relativenumber = true
