set -g base-index 1
setw -g pane-base-index 1

setw -g mode-keys vi

bind 'v' copy-mode
bind '&' kill-window
bind 'x' kill-pane

set -g allow-passthrough on
set -g set-clipboard external

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'rose-pine/tmux'

set -g @rose_pine_variant 'main' # Options are 'main', 'moon' or 'dawn'

run '~/.tmux/plugins/tpm/tpm'
